
name: Node.js Package

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: ./node_modules
          key: dependencies-${{ runner.os }}-node-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install -g pnpm && pnpm i --frozen-lockfile

      - name: Build artifact
        run: npm run build:prod

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
