name: Test CI

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to report coverage for'
        required: false
      publish_type:
        description: 'Tags of package'
        required: true
        type: choice
        default: 'none'
        options:
          - beta
          - latest
          - none

jobs:
  converage-unitests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: ./node_modules
          key: dependencies-${{ runner.os }}-node-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install -g pnpm && pnpm i --frozen-lockfile

      - name: Build
        run: npm run build:dev

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Run tests with junit
        run: npm run test:junit

      - name: Inject classname into testcase
        run: |
          sed -i 's/<testcase name="/<testcase classname="path-treeify.Default" name="/g' reports/junit.xml

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./reports/coverage/lcov.info

      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: AVA Tests
          path: reports/junit.xml
          reporter: java-junit
          fail-on-error: false

  trigger-build-workflow:
    needs: ['converage-unitests']
    if: inputs.publish_type != 'none'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const publishType = '${{ inputs.publish_type }}';
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-package.yml',
              ref: 'main',
              inputs: {
                publish_type: publishType,
              }
            })
